stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build_job:
  stage: build
  tags:
    - master
  image: node:11
  only:
    - master
  script:
    - echo "build ......"
    - npm install --progress=false --registry=https://registry.npm.taobao.org
    - npm run build
    - echo "done"
  artifacts:
    paths:
      - dist

test_job:
  stage: test
  tags:
    - master
  only:
    - master
  script:
    - echo "test ......"
    - echo "done"

deploy_job:
  stage: deploy
  tags:
    - master
  image: centos
  only:
    - master
  script:
    - echo "deploy ......"
    # - yum update -y
    - rm -rf /usr/share/nginx/html/www/dist
    - mkdir /usr/share/nginx/html/www/dist
    - cp ./dist /usr/share/nginx/html/www/dist
    - echo "done"
