stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build_job:
  stage: build
  tags:
    - master
  image: node:11
  only:
    - master
  script:
    - echo "build ......"
    - npm install --progress=false --registry=https://registry.npm.taobao.org
    - npm run build
    - echo "done"
  artifacts:
    paths:
      - dist

test_job:
  stage: test
  tags:
    - master
  only:
    - master
  script:
    - echo "test ......"
    - echo "done"

deploy_job:
  stage: deploy
  tags:
    - master
  image: centos
  only:
    - master
  script:
    - echo "deploy ......"
    # - yum update -y
    - yum install expect -y
    - yum install openssh-clients -y
    - chmod +x ./scp.sh
    - ./scp.sh ./dist /usr/share/nginx/html/www 211.159.166.222 $G13820066708
    - echo "done"
